[workspace]
members = [
    'node',
    'pallets/certification',
    'pallets/identity',
    'pallets/ud-accounts-storage',
    'pallets/universal-dividend',
    'runtime',
]
[profile.dev]
opt-level = 3
[profile.release]
panic = 'unwind'
