version: "3.5"

services:
  duniter-v2s:
    container_name: duniter-v2s
    image: duniter/duniter-v2s:v0.1.0
    ports:
      # telemetry
      - 9615:9615
      # rpc
      - 9933:9933
      # rpc-ws
      - 9944:9944
      # p2p
      - 30333:30333
    environment:
      DUNITER_INSTANCE_NAME: "duniter_local"
      DUNITER_CHAIN_NAME: "dev"
      #DUNITER_DISABLE_PROMETHEUS: "false"
    volumes:
      - duniter-local-data:/var/lib/duniter

volumes:
  duniter-local-data:
