[package]
name = 'common-runtime'
description = 'Common code shared between all runtimes'
license = 'GPL-3.0-only'
version = '0.8.0-dev'
authors = ['Axiom-Team Developers <https://axiom-team.fr>']
edition = '2018'

[features]
runtime-benchmarks = [
    'frame-support/runtime-benchmarks',
    'frame-system/runtime-benchmarks',
    'pallet-certification/runtime-benchmarks',
    'pallet-duniter-wot/runtime-benchmarks',
    'pallet-identity/runtime-benchmarks',
    'pallet-membership/runtime-benchmarks',
    'pallet-ud-accounts-storage/runtime-benchmarks',
    'sp-runtime/runtime-benchmarks',
]
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-certification/std',
    'pallet-duniter-wot/std',
    'pallet-identity/std',
    'pallet-membership/std',
    'pallet-ud-accounts-storage/std',
    'serde',
    'sp-arithmetic/std',
    'sp-core/std',
    'sp-membership/std',
    'sp-runtime/std',
    'sp-std/std'
]

[dependencies]
pallet-certification = { path = '../../pallets/certification', default-features = false }
pallet-duniter-wot = { path = '../../pallets/duniter-wot', default-features = false }
pallet-identity = { path = '../../pallets/identity', default-features = false }
pallet-membership = { path = '../../pallets/membership', default-features = false }
pallet-ud-accounts-storage = { path = '../../pallets/ud-accounts-storage', default-features = false }
sp-membership = { path = '../../primitives/membership', default-features = false }

# Crates.io
smallvec = "1.6.1"

# Substrate
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.3.1'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/librelois/substrate.git'
branch = 'duniter-monthly-2022-01'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/librelois/substrate.git'
branch = 'duniter-monthly-2022-01'

[dependencies.pallet-session]
default-features = false
features = ["historical"]
git = 'https://github.com/librelois/substrate.git'
branch = 'duniter-monthly-2022-01'

[dependencies.serde]
version = "1.0.101"
optional = true
features = ["derive"]

[dependencies.sp-arithmetic]
default-features = false
git = 'https://github.com/librelois/substrate.git'
branch = 'duniter-monthly-2022-01'

[dependencies.sp-consensus-babe]
default-features = false
git = 'https://github.com/librelois/substrate.git'
branch = 'duniter-monthly-2022-01'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/librelois/substrate.git'
branch = 'duniter-monthly-2022-01'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/librelois/substrate.git'
branch = 'duniter-monthly-2022-01'

[dependencies.sp-staking]
default-features = false
git = 'https://github.com/librelois/substrate.git'
branch = 'duniter-monthly-2022-01'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/librelois/substrate.git'
branch = 'duniter-monthly-2022-01'
