version: "3.5"

services:
  duniter-1:
    container_name: duniter-1
    image: duniter/duniter-v2s:local
    ports:
      # telemetry
      - "127.0.0.1:9615:9615"
      # rpc
      - "127.0.0.1:9933:9933"
      # rpc-ws
      - "127.0.0.1:9944:9944"
      # p2p
      - "30333:30333"
    environment:
      DUNITER_INSTANCE_NAME: "my_instance"
      DUNITER_CHAIN_NAME: "local"
      #DUNITER_DISABLE_PROMETHEUS: "false"
    command: ["--alice", "--node-key", "0000000000000000000000000000000000000000000000000000000000000001"]
    volumes:
      - data:/var/lib/lc-core
    networks:
      app_net:
        ipv4_address: 172.16.238.10


  duniter-2:
    container_name: duniter-2
    image: duniter/duniter-v2s:local
    ports:
      # telemetry
      - "127.0.0.1:9616:9615"
      # rpc
      - "127.0.0.1:9934:9933"
      # rpc-ws
      - "127.0.0.1:9945:9944"
      # p2p
      - "30334:30333"
    environment:
      DUNITER_INSTANCE_NAME: "my_instance"
      DUNITER_CHAIN_NAME: "local"
      #DUNITER_DISABLE_PROMETHEUS: "false"
    command: ["--bob", "--bootnodes", "/ip4/172.16.238.10/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"]
    volumes:
      - data2:/var/lib/lc-core
    networks:
      app_net:
        ipv4_address: 172.16.238.11

volumes:
  data:
  data2:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
