# This is a docker template for running a gdev mirror

version: "3.5"

services:
  duniter-rpc:
    image: duniter/duniter-v2s:latest
    restart: unless-stopped
    ports:
      # telemetry
      - 127.0.0.1:9615:9615
      # rpc
      - 127.0.0.1:9933:9933
      # rpc-ws
      - 127.0.0.1:9944:9944
      # p2p
      - 30333:30333
    volumes:
      - ./node.key:/etc/duniter/node.key
      - duniter-rpc-data:/var/lib/duniter/
    environment:
      - DUNITER_CHAIN_NAME=gdev
      # SERVER_DOMAIN should be replaced by a domain name that point on your server
      - DUNITER_PUBLIC_ADDR=/dns/${SERVER_DOMAIN?SERVER_DOMAIN should be set}/tcp/30333/ws

volumes:
  duniter-rpc-data:
