version: "3.5"

services:
  duniter-rpc:
    image: duniter/duniter-v2s:latest
    restart: unless-stopped
    ports:
      # telemetry
      - 127.0.0.1:9615:9615
      # rpc
      - 127.0.0.1:9933:9933
      # rpc-ws
      - 127.0.0.1:9944:9944
      # p2p
      - 30333:30333
    volumes:
      - ./node.key:/etc/duniter/validator-node.key
      - duniter-rpc-data:/var/lib/duniter/
    environment:
      - DUNITER_CHAIN_NAME=gdev
      # RPC_SERVER_DOMAIN should be replaced by a domain name that point on your server
      - DUNITER_PUBLIC_ADDR=/dns/${RPC_SERVER_DOMAIN?RPC_SERVER_DOMAIN should be set}/tcp/30333/ws

  duniter-validator:
    image: duniter/duniter-v2s:latest
    restart: unless-stopped
    ports:
      # telemetry
      - 127.0.0.1:9616:9615
      # rpc
      - 127.0.0.1:9934:9933
      # rpc-ws
      - 127.0.0.1:9945:9944
      # p2p
      - 30334:30333
    volumes:
      - ./node.key:/etc/duniter/validator-node.key
      - duniter-validator-data:/var/lib/duniter/
    environment:
      - DUNITER_CHAIN_NAME=gdev
      # VALIDATOR_SERVER_DOMAIN should be replaced by a domain name that point on your server
      - DUNITER_PUBLIC_ADDR=/dns/${VALIDATOR_SERVER_DOMAIN?VALIDATOR_SERVER_DOMAIN should be set}/tcp/30333
      - DUNITER_VALIDATOR=true
    command:
      - "--pruning=14400"
